 SELECT TOP 10 * FROM S_HREMPLOYEES sh
 SELECT UPPER(FIRST_NAME) from S_HREMPLOYEES sh
SELECT LOWER(LAST_NAME) from S_HREMPLOYEES sh
SELECT TRIM(FIRST_NAME) FROM S_HREMPLOYEES
SELECT RTRIM(FIRST_NAME) FROM S_HREMPLOYEES sh
SELECT LTRIM(EMPLOYEE_ID) FROM S_HREMPLOYEES sh
 SELECT LEN(LAST_NAME) FROM S_HREMPLOYEES sh
 SELECT REPLACE('STEVEN','STEVEN','SOUKYABV') FROM S_HREMPLOYEES sh
SELECT REPLACE('STEVEN','STEVEN','SOUKYA') FROM S_HREMPLOYEES sh

SELECT CASE WHEN DEPARTMENT_ID =90 THEN 'IT'
WHEN DEPARTMENT_ID =100 THEN 'HR'
WHEN DEPARTMENT_ID =60 THEN 'LOAN'
ELSE 'OTHERS'
END 
FROM dlithe.dbo.S_HREMPLOYEES
SELECT SUBSTRING('SPOORTHY GOWDA',1,15) AS FIRST_NAME FROM dlithe.dbo.S_HREMPLOYEES